# =========================================================
#       PLAY -- Deploy SIWAPP somwhere
# ---------------------------------------------------------

- name: SETUP SIWAPP LOAD GENERATOR FOR DEPLOY
  hosts: localhost

  tasks:
  - name: Using variable input to create terraform template file
    ansible.builtin.template:
      src: siwapp-loadgen/siwapp-loadgen-secrets.j2
      dest: siwapp-loadgen/siwapp-loadgen-secrets.yaml

- name: Install microk8s --classic
  community.general.snap:
    name: microk8s
    classic: true

