apiVersion: apps/v1
kind: Deployment
metadata:
  name: siwapp-loadgen-deployment
  labels:
    app: siwapp-loadgen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: siwapp-loadgen
  template:
    metadata:
      labels:
        app: siwapp-loadgen
    spec:
      containers:
      - name: siwapp-loadgen
        image: cmacrdu/pegasus-invoicing-load:latest
        env:
          - name: VC_URL
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: VC_URL
          - name: VC_USER
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: VC_USER
          - name: VC_PW
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: VC_PW
          - name: VM_NAME_FILTER
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: VM_NAME_FILTER
          - name: SIWAPP_USER
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: SIWAPP_USER
          - name: SIWAPP_PW
            valueFrom:
              secretKeyRef:
                name: siwapp-loadgen
                key: SIWAPP_PW